title: Harim Shin
author: 
  name: Harim Shin
  email: "vero.harim.shin@gmail.com"
minima:
  social_links:
    - { platform: linkedin,  user_url: "https://linkedin.com/in/harim-shin/" }
logo: /assets/img/headshot_circle.png
show_downloads: true
theme: jekyll-theme-minimal
