title: Harim Shin
description: email: vero.harim.shin@gmail.com | LinkedIn: linkedin.com/in/harim-shin/ | Resume is available upon request.
logo: /assets/img/headshot_circle.png
show_downloads: true
theme: jekyll-theme-minimal
